# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd4382b0129ae73395c1e9db7387aeefab5405c9474c183941fcf4f327a233b618c58ce5f705ced113b176e5f575575d073e0890bb0286afd5b80999a2fb639

test:
  secret_key_base: 8afcf23fe72a7ade6fdb3c960266ae1c283254bdac6eb92dbd5af931046797e49c88b674e793eec735d43ba8803d77accad7922fcfb13c9f6ea671b64c640364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
